# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.

permalink:           "/:year/:month/:title"
relative_permalinks: true
markdown: redcarpet
redcarpet:
  extensions: ["smart", "tables", "no_intra_emphasis", "fenced_code_blocks", "autolink", "strikethrough", "superscript", "with_toc_data"]

# Setup
title:               techSonian
tagline:             "Sonian's Technology Blog. All about forging ahead in the cloud."
description:         "An early innovator in cloud-based archiving, Sonian preserves, protects and presents the worldâ€™s information."
url:                 http://iantruslove.github.io
baseurl:             '/techsonian'
paginate:            5

# About/contact
author:
  name:              Sonian
  url:               http://sonian.com
  email:             tech@sonian.com

# Custom vars
version:             1.0.0
